# Generated by Django 4.2.5 on 2023-09-15 19:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_plan_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='post_images'),
        ),
    ]
