# Generated by Django 4.2.5 on 2023-09-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_size_thumbnailsize_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
    ]
